// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/correspondence/v1/correspondence.proto

package correspondencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CorrespondenceService_CreateCorrespondence_FullMethodName  = "/correspondence.v1.CorrespondenceService/CreateCorrespondence"
	CorrespondenceService_UpdateCorrespondence_FullMethodName  = "/correspondence.v1.CorrespondenceService/UpdateCorrespondence"
	CorrespondenceService_ArchiveCorrespondence_FullMethodName = "/correspondence.v1.CorrespondenceService/ArchiveCorrespondence"
	CorrespondenceService_GetCorrespondence_FullMethodName     = "/correspondence.v1.CorrespondenceService/GetCorrespondence"
	CorrespondenceService_ListCorrespondences_FullMethodName   = "/correspondence.v1.CorrespondenceService/ListCorrespondences"
)

// CorrespondenceServiceClient is the client API for CorrespondenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CorrespondenceServiceClient interface {
	CreateCorrespondence(ctx context.Context, in *CreateCorrespondenceRequest, opts ...grpc.CallOption) (*CreateCorrespondenceResponse, error)
	UpdateCorrespondence(ctx context.Context, in *UpdateCorrespondenceRequest, opts ...grpc.CallOption) (*UpdateCorrespondenceResponse, error)
	ArchiveCorrespondence(ctx context.Context, in *ArchiveCorrespondenceRequest, opts ...grpc.CallOption) (*ArchiveCorrespondenceResponse, error)
	GetCorrespondence(ctx context.Context, in *GetCorrespondenceRequest, opts ...grpc.CallOption) (*GetCorrespondenceResponse, error)
	ListCorrespondences(ctx context.Context, in *ListCorrespondencesRequest, opts ...grpc.CallOption) (*ListCorrespondencesResponse, error)
}

type correspondenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCorrespondenceServiceClient(cc grpc.ClientConnInterface) CorrespondenceServiceClient {
	return &correspondenceServiceClient{cc}
}

func (c *correspondenceServiceClient) CreateCorrespondence(ctx context.Context, in *CreateCorrespondenceRequest, opts ...grpc.CallOption) (*CreateCorrespondenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCorrespondenceResponse)
	err := c.cc.Invoke(ctx, CorrespondenceService_CreateCorrespondence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *correspondenceServiceClient) UpdateCorrespondence(ctx context.Context, in *UpdateCorrespondenceRequest, opts ...grpc.CallOption) (*UpdateCorrespondenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCorrespondenceResponse)
	err := c.cc.Invoke(ctx, CorrespondenceService_UpdateCorrespondence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *correspondenceServiceClient) ArchiveCorrespondence(ctx context.Context, in *ArchiveCorrespondenceRequest, opts ...grpc.CallOption) (*ArchiveCorrespondenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveCorrespondenceResponse)
	err := c.cc.Invoke(ctx, CorrespondenceService_ArchiveCorrespondence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *correspondenceServiceClient) GetCorrespondence(ctx context.Context, in *GetCorrespondenceRequest, opts ...grpc.CallOption) (*GetCorrespondenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCorrespondenceResponse)
	err := c.cc.Invoke(ctx, CorrespondenceService_GetCorrespondence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *correspondenceServiceClient) ListCorrespondences(ctx context.Context, in *ListCorrespondencesRequest, opts ...grpc.CallOption) (*ListCorrespondencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCorrespondencesResponse)
	err := c.cc.Invoke(ctx, CorrespondenceService_ListCorrespondences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CorrespondenceServiceServer is the server API for CorrespondenceService service.
// All implementations must embed UnimplementedCorrespondenceServiceServer
// for forward compatibility.
type CorrespondenceServiceServer interface {
	CreateCorrespondence(context.Context, *CreateCorrespondenceRequest) (*CreateCorrespondenceResponse, error)
	UpdateCorrespondence(context.Context, *UpdateCorrespondenceRequest) (*UpdateCorrespondenceResponse, error)
	ArchiveCorrespondence(context.Context, *ArchiveCorrespondenceRequest) (*ArchiveCorrespondenceResponse, error)
	GetCorrespondence(context.Context, *GetCorrespondenceRequest) (*GetCorrespondenceResponse, error)
	ListCorrespondences(context.Context, *ListCorrespondencesRequest) (*ListCorrespondencesResponse, error)
	mustEmbedUnimplementedCorrespondenceServiceServer()
}

// UnimplementedCorrespondenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCorrespondenceServiceServer struct{}

func (UnimplementedCorrespondenceServiceServer) CreateCorrespondence(context.Context, *CreateCorrespondenceRequest) (*CreateCorrespondenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCorrespondence not implemented")
}
func (UnimplementedCorrespondenceServiceServer) UpdateCorrespondence(context.Context, *UpdateCorrespondenceRequest) (*UpdateCorrespondenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCorrespondence not implemented")
}
func (UnimplementedCorrespondenceServiceServer) ArchiveCorrespondence(context.Context, *ArchiveCorrespondenceRequest) (*ArchiveCorrespondenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveCorrespondence not implemented")
}
func (UnimplementedCorrespondenceServiceServer) GetCorrespondence(context.Context, *GetCorrespondenceRequest) (*GetCorrespondenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCorrespondence not implemented")
}
func (UnimplementedCorrespondenceServiceServer) ListCorrespondences(context.Context, *ListCorrespondencesRequest) (*ListCorrespondencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCorrespondences not implemented")
}
func (UnimplementedCorrespondenceServiceServer) mustEmbedUnimplementedCorrespondenceServiceServer() {}
func (UnimplementedCorrespondenceServiceServer) testEmbeddedByValue()                               {}

// UnsafeCorrespondenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CorrespondenceServiceServer will
// result in compilation errors.
type UnsafeCorrespondenceServiceServer interface {
	mustEmbedUnimplementedCorrespondenceServiceServer()
}

func RegisterCorrespondenceServiceServer(s grpc.ServiceRegistrar, srv CorrespondenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedCorrespondenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CorrespondenceService_ServiceDesc, srv)
}

func _CorrespondenceService_CreateCorrespondence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCorrespondenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorrespondenceServiceServer).CreateCorrespondence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorrespondenceService_CreateCorrespondence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorrespondenceServiceServer).CreateCorrespondence(ctx, req.(*CreateCorrespondenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorrespondenceService_UpdateCorrespondence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCorrespondenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorrespondenceServiceServer).UpdateCorrespondence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorrespondenceService_UpdateCorrespondence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorrespondenceServiceServer).UpdateCorrespondence(ctx, req.(*UpdateCorrespondenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorrespondenceService_ArchiveCorrespondence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveCorrespondenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorrespondenceServiceServer).ArchiveCorrespondence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorrespondenceService_ArchiveCorrespondence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorrespondenceServiceServer).ArchiveCorrespondence(ctx, req.(*ArchiveCorrespondenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorrespondenceService_GetCorrespondence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCorrespondenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorrespondenceServiceServer).GetCorrespondence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorrespondenceService_GetCorrespondence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorrespondenceServiceServer).GetCorrespondence(ctx, req.(*GetCorrespondenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorrespondenceService_ListCorrespondences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCorrespondencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorrespondenceServiceServer).ListCorrespondences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorrespondenceService_ListCorrespondences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorrespondenceServiceServer).ListCorrespondences(ctx, req.(*ListCorrespondencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CorrespondenceService_ServiceDesc is the grpc.ServiceDesc for CorrespondenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CorrespondenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "correspondence.v1.CorrespondenceService",
	HandlerType: (*CorrespondenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCorrespondence",
			Handler:    _CorrespondenceService_CreateCorrespondence_Handler,
		},
		{
			MethodName: "UpdateCorrespondence",
			Handler:    _CorrespondenceService_UpdateCorrespondence_Handler,
		},
		{
			MethodName: "ArchiveCorrespondence",
			Handler:    _CorrespondenceService_ArchiveCorrespondence_Handler,
		},
		{
			MethodName: "GetCorrespondence",
			Handler:    _CorrespondenceService_GetCorrespondence_Handler,
		},
		{
			MethodName: "ListCorrespondences",
			Handler:    _CorrespondenceService_ListCorrespondences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/correspondence/v1/correspondence.proto",
}
