// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/assessment/v1/assessment.proto

package assessmentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssessmentService_CreateAssessment_FullMethodName      = "/assessment.v1.AssessmentService/CreateAssessment"
	AssessmentService_UpdateAssessment_FullMethodName      = "/assessment.v1.AssessmentService/UpdateAssessment"
	AssessmentService_GetAssessment_FullMethodName         = "/assessment.v1.AssessmentService/GetAssessment"
	AssessmentService_GetStudentAssessments_FullMethodName = "/assessment.v1.AssessmentService/GetStudentAssessments"
	AssessmentService_GetSubjectAssessments_FullMethodName = "/assessment.v1.AssessmentService/GetSubjectAssessments"
	AssessmentService_ListAssessments_FullMethodName       = "/assessment.v1.AssessmentService/ListAssessments"
	AssessmentService_GetStudentAverage_FullMethodName     = "/assessment.v1.AssessmentService/GetStudentAverage"
)

// AssessmentServiceClient is the client API for AssessmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssessmentServiceClient interface {
	CreateAssessment(ctx context.Context, in *CreateAssessmentRequest, opts ...grpc.CallOption) (*CreateAssessmentResponse, error)
	UpdateAssessment(ctx context.Context, in *UpdateAssessmentRequest, opts ...grpc.CallOption) (*UpdateAssessmentResponse, error)
	GetAssessment(ctx context.Context, in *GetAssessmentRequest, opts ...grpc.CallOption) (*GetAssessmentResponse, error)
	GetStudentAssessments(ctx context.Context, in *GetStudentAssessmentsRequest, opts ...grpc.CallOption) (*GetStudentAssessmentsResponse, error)
	GetSubjectAssessments(ctx context.Context, in *GetSubjectAssessmentsRequest, opts ...grpc.CallOption) (*GetSubjectAssessmentsResponse, error)
	ListAssessments(ctx context.Context, in *ListAssessmentsRequest, opts ...grpc.CallOption) (*ListAssessmentsResponse, error)
	GetStudentAverage(ctx context.Context, in *GetStudentAverageRequest, opts ...grpc.CallOption) (*GetStudentAverageResponse, error)
}

type assessmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssessmentServiceClient(cc grpc.ClientConnInterface) AssessmentServiceClient {
	return &assessmentServiceClient{cc}
}

func (c *assessmentServiceClient) CreateAssessment(ctx context.Context, in *CreateAssessmentRequest, opts ...grpc.CallOption) (*CreateAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssessmentResponse)
	err := c.cc.Invoke(ctx, AssessmentService_CreateAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) UpdateAssessment(ctx context.Context, in *UpdateAssessmentRequest, opts ...grpc.CallOption) (*UpdateAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssessmentResponse)
	err := c.cc.Invoke(ctx, AssessmentService_UpdateAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GetAssessment(ctx context.Context, in *GetAssessmentRequest, opts ...grpc.CallOption) (*GetAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssessmentResponse)
	err := c.cc.Invoke(ctx, AssessmentService_GetAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GetStudentAssessments(ctx context.Context, in *GetStudentAssessmentsRequest, opts ...grpc.CallOption) (*GetStudentAssessmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentAssessmentsResponse)
	err := c.cc.Invoke(ctx, AssessmentService_GetStudentAssessments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GetSubjectAssessments(ctx context.Context, in *GetSubjectAssessmentsRequest, opts ...grpc.CallOption) (*GetSubjectAssessmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubjectAssessmentsResponse)
	err := c.cc.Invoke(ctx, AssessmentService_GetSubjectAssessments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) ListAssessments(ctx context.Context, in *ListAssessmentsRequest, opts ...grpc.CallOption) (*ListAssessmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssessmentsResponse)
	err := c.cc.Invoke(ctx, AssessmentService_ListAssessments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GetStudentAverage(ctx context.Context, in *GetStudentAverageRequest, opts ...grpc.CallOption) (*GetStudentAverageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentAverageResponse)
	err := c.cc.Invoke(ctx, AssessmentService_GetStudentAverage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssessmentServiceServer is the server API for AssessmentService service.
// All implementations must embed UnimplementedAssessmentServiceServer
// for forward compatibility.
type AssessmentServiceServer interface {
	CreateAssessment(context.Context, *CreateAssessmentRequest) (*CreateAssessmentResponse, error)
	UpdateAssessment(context.Context, *UpdateAssessmentRequest) (*UpdateAssessmentResponse, error)
	GetAssessment(context.Context, *GetAssessmentRequest) (*GetAssessmentResponse, error)
	GetStudentAssessments(context.Context, *GetStudentAssessmentsRequest) (*GetStudentAssessmentsResponse, error)
	GetSubjectAssessments(context.Context, *GetSubjectAssessmentsRequest) (*GetSubjectAssessmentsResponse, error)
	ListAssessments(context.Context, *ListAssessmentsRequest) (*ListAssessmentsResponse, error)
	GetStudentAverage(context.Context, *GetStudentAverageRequest) (*GetStudentAverageResponse, error)
	mustEmbedUnimplementedAssessmentServiceServer()
}

// UnimplementedAssessmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssessmentServiceServer struct{}

func (UnimplementedAssessmentServiceServer) CreateAssessment(context.Context, *CreateAssessmentRequest) (*CreateAssessmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAssessment not implemented")
}
func (UnimplementedAssessmentServiceServer) UpdateAssessment(context.Context, *UpdateAssessmentRequest) (*UpdateAssessmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssessment not implemented")
}
func (UnimplementedAssessmentServiceServer) GetAssessment(context.Context, *GetAssessmentRequest) (*GetAssessmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssessment not implemented")
}
func (UnimplementedAssessmentServiceServer) GetStudentAssessments(context.Context, *GetStudentAssessmentsRequest) (*GetStudentAssessmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentAssessments not implemented")
}
func (UnimplementedAssessmentServiceServer) GetSubjectAssessments(context.Context, *GetSubjectAssessmentsRequest) (*GetSubjectAssessmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubjectAssessments not implemented")
}
func (UnimplementedAssessmentServiceServer) ListAssessments(context.Context, *ListAssessmentsRequest) (*ListAssessmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAssessments not implemented")
}
func (UnimplementedAssessmentServiceServer) GetStudentAverage(context.Context, *GetStudentAverageRequest) (*GetStudentAverageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentAverage not implemented")
}
func (UnimplementedAssessmentServiceServer) mustEmbedUnimplementedAssessmentServiceServer() {}
func (UnimplementedAssessmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeAssessmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssessmentServiceServer will
// result in compilation errors.
type UnsafeAssessmentServiceServer interface {
	mustEmbedUnimplementedAssessmentServiceServer()
}

func RegisterAssessmentServiceServer(s grpc.ServiceRegistrar, srv AssessmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAssessmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssessmentService_ServiceDesc, srv)
}

func _AssessmentService_CreateAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).CreateAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_CreateAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).CreateAssessment(ctx, req.(*CreateAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_UpdateAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).UpdateAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_UpdateAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).UpdateAssessment(ctx, req.(*UpdateAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GetAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GetAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GetAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GetAssessment(ctx, req.(*GetAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GetStudentAssessments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentAssessmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GetStudentAssessments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GetStudentAssessments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GetStudentAssessments(ctx, req.(*GetStudentAssessmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GetSubjectAssessments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubjectAssessmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GetSubjectAssessments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GetSubjectAssessments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GetSubjectAssessments(ctx, req.(*GetSubjectAssessmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_ListAssessments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssessmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).ListAssessments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_ListAssessments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).ListAssessments(ctx, req.(*ListAssessmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GetStudentAverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentAverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GetStudentAverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GetStudentAverage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GetStudentAverage(ctx, req.(*GetStudentAverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssessmentService_ServiceDesc is the grpc.ServiceDesc for AssessmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssessmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assessment.v1.AssessmentService",
	HandlerType: (*AssessmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAssessment",
			Handler:    _AssessmentService_CreateAssessment_Handler,
		},
		{
			MethodName: "UpdateAssessment",
			Handler:    _AssessmentService_UpdateAssessment_Handler,
		},
		{
			MethodName: "GetAssessment",
			Handler:    _AssessmentService_GetAssessment_Handler,
		},
		{
			MethodName: "GetStudentAssessments",
			Handler:    _AssessmentService_GetStudentAssessments_Handler,
		},
		{
			MethodName: "GetSubjectAssessments",
			Handler:    _AssessmentService_GetSubjectAssessments_Handler,
		},
		{
			MethodName: "ListAssessments",
			Handler:    _AssessmentService_ListAssessments_Handler,
		},
		{
			MethodName: "GetStudentAverage",
			Handler:    _AssessmentService_GetStudentAverage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/assessment/v1/assessment.proto",
}
