// src/events/EventCatalog.js
export const EVENTS = {
  // Auth
  AUTH_LOGGED_IN: 'AUTH_LOGGED_IN',
  AUTH_LOGGED_OUT: 'AUTH_LOGGED_OUT',

  // Teaching
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_ENDED: 'SESSION_ENDED',
  JOURNAL_DRAFT_SAVED: 'JOURNAL_DRAFT_SAVED',
  JOURNAL_FINALIZED: 'JOURNAL_FINALIZED',

  // Attendance
  ATTENDANCE_DRAFT_SAVED: 'ATTENDANCE_DRAFT_SAVED',
  ATTENDANCE_SUBMITTED: 'ATTENDANCE_SUBMITTED',
  ATTENDANCE_RECORD_UPDATED: 'ATTENDANCE_RECORD_UPDATED',

  // Assessment
  GRADE_CALCULATED: 'GRADE_CALCULATED',
  ASSESSMENT_FINALIZED: 'ASSESSMENT_FINALIZED',

  // Student Progress
  TEACHER_NOTE_ADDED: 'TEACHER_NOTE_ADDED',
  ACHIEVEMENT_ADDED: 'ACHIEVEMENT_ADDED',
  VIOLATION_ADDED: 'VIOLATION_ADDED',

  // Inventory
  ASSET_BORROWED: 'ASSET_BORROWED',
  ASSET_RETURNED: 'ASSET_RETURNED',
  ASSET_DAMAGED: 'ASSET_DAMAGED',

  // Reporting
  REPORT_GENERATED: 'REPORT_GENERATED',
  DASHBOARD_DATA_UPDATED: 'DASHBOARD_DATA_UPDATED',

  // Context
  CONTEXT_CHANGED: 'CONTEXT_CHANGED',
}

export const EventCatalog = {
  getAllEvents: () => Object.values(EVENTS),
  isValid: (event) => Object.values(EVENTS).includes(event),
}
