// Auth Events
export const EVENT_USER_LOGGED_IN = 'USER_LOGGED_IN'
export const EVENT_USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const EVENT_SESSION_RESTORED = 'SESSION_RESTORED'
export const EVENT_SESSION_EXPIRED = 'SESSION_EXPIRED'
export const EVENT_AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'
// Context Events
export const EVENT_CONTEXT_SELECTED = 'CONTEXT_SELECTED'
export const EVENT_CONTEXT_CLEARED = 'CONTEXT_CLEARED'

// Teaching Events
export const EVENT_TEACHING_SESSION_STARTED = 'TEACHING_SESSION_STARTED'
export const EVENT_TEACHING_SESSION_ENDED = 'TEACHING_SESSION_ENDED'

// Attendance Events
export const EVENT_ATTENDANCE_DRAFTED = 'ATTENDANCE_DRAFTED'
export const EVENT_ATTENDANCE_SUBMITTED = 'ATTENDANCE_SUBMITTED'

// Journal Events
export const EVENT_JOURNAL_CREATED = 'JOURNAL_CREATED'
export const EVENT_JOURNAL_SUBMITTED = 'JOURNAL_SUBMITTED'

// Assessment Events
export const EVENT_ASSESSMENT_FINALIZED = 'ASSESSMENT_FINALIZED'

// Progress Events
export const EVENT_PROGRESS_RECORDED = 'PROGRESS_RECORDED'

// Inventory Events
export const EVENT_ASSET_DAMAGE_REPORTED = 'ASSET_DAMAGE_REPORTED'

// Teacher Document Events
export const EVENT_TEACHER_DOCUMENT_CREATED = 'TEACHER_DOCUMENT_CREATED'
export const EVENT_TEACHER_DOCUMENT_DELETED = 'TEACHER_DOCUMENT_DELETED'
