// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/inventory/v1/inventory.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_CreateAsset_FullMethodName  = "/inventory.v1.InventoryService/CreateAsset"
	InventoryService_MoveAsset_FullMethodName    = "/inventory.v1.InventoryService/MoveAsset"
	InventoryService_BorrowAsset_FullMethodName  = "/inventory.v1.InventoryService/BorrowAsset"
	InventoryService_ReturnAsset_FullMethodName  = "/inventory.v1.InventoryService/ReturnAsset"
	InventoryService_ReportDamage_FullMethodName = "/inventory.v1.InventoryService/ReportDamage"
	InventoryService_DisposeAsset_FullMethodName = "/inventory.v1.InventoryService/DisposeAsset"
	InventoryService_GetAsset_FullMethodName     = "/inventory.v1.InventoryService/GetAsset"
	InventoryService_ListAssets_FullMethodName   = "/inventory.v1.InventoryService/ListAssets"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*CreateAssetResponse, error)
	MoveAsset(ctx context.Context, in *MoveAssetRequest, opts ...grpc.CallOption) (*MoveAssetResponse, error)
	BorrowAsset(ctx context.Context, in *BorrowAssetRequest, opts ...grpc.CallOption) (*BorrowAssetResponse, error)
	ReturnAsset(ctx context.Context, in *ReturnAssetRequest, opts ...grpc.CallOption) (*ReturnAssetResponse, error)
	ReportDamage(ctx context.Context, in *ReportDamageRequest, opts ...grpc.CallOption) (*ReportDamageResponse, error)
	DisposeAsset(ctx context.Context, in *DisposeAssetRequest, opts ...grpc.CallOption) (*DisposeAssetResponse, error)
	GetAsset(ctx context.Context, in *GetAssetRequest, opts ...grpc.CallOption) (*GetAssetResponse, error)
	ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*ListAssetsResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*CreateAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssetResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) MoveAsset(ctx context.Context, in *MoveAssetRequest, opts ...grpc.CallOption) (*MoveAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveAssetResponse)
	err := c.cc.Invoke(ctx, InventoryService_MoveAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) BorrowAsset(ctx context.Context, in *BorrowAssetRequest, opts ...grpc.CallOption) (*BorrowAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BorrowAssetResponse)
	err := c.cc.Invoke(ctx, InventoryService_BorrowAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReturnAsset(ctx context.Context, in *ReturnAssetRequest, opts ...grpc.CallOption) (*ReturnAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnAssetResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReturnAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReportDamage(ctx context.Context, in *ReportDamageRequest, opts ...grpc.CallOption) (*ReportDamageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportDamageResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReportDamage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) DisposeAsset(ctx context.Context, in *DisposeAssetRequest, opts ...grpc.CallOption) (*DisposeAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisposeAssetResponse)
	err := c.cc.Invoke(ctx, InventoryService_DisposeAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetAsset(ctx context.Context, in *GetAssetRequest, opts ...grpc.CallOption) (*GetAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssetResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*ListAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssetsResponse)
	err := c.cc.Invoke(ctx, InventoryService_ListAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
type InventoryServiceServer interface {
	CreateAsset(context.Context, *CreateAssetRequest) (*CreateAssetResponse, error)
	MoveAsset(context.Context, *MoveAssetRequest) (*MoveAssetResponse, error)
	BorrowAsset(context.Context, *BorrowAssetRequest) (*BorrowAssetResponse, error)
	ReturnAsset(context.Context, *ReturnAssetRequest) (*ReturnAssetResponse, error)
	ReportDamage(context.Context, *ReportDamageRequest) (*ReportDamageResponse, error)
	DisposeAsset(context.Context, *DisposeAssetRequest) (*DisposeAssetResponse, error)
	GetAsset(context.Context, *GetAssetRequest) (*GetAssetResponse, error)
	ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) CreateAsset(context.Context, *CreateAssetRequest) (*CreateAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAsset not implemented")
}
func (UnimplementedInventoryServiceServer) MoveAsset(context.Context, *MoveAssetRequest) (*MoveAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveAsset not implemented")
}
func (UnimplementedInventoryServiceServer) BorrowAsset(context.Context, *BorrowAssetRequest) (*BorrowAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BorrowAsset not implemented")
}
func (UnimplementedInventoryServiceServer) ReturnAsset(context.Context, *ReturnAssetRequest) (*ReturnAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnAsset not implemented")
}
func (UnimplementedInventoryServiceServer) ReportDamage(context.Context, *ReportDamageRequest) (*ReportDamageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportDamage not implemented")
}
func (UnimplementedInventoryServiceServer) DisposeAsset(context.Context, *DisposeAssetRequest) (*DisposeAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisposeAsset not implemented")
}
func (UnimplementedInventoryServiceServer) GetAsset(context.Context, *GetAssetRequest) (*GetAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAsset not implemented")
}
func (UnimplementedInventoryServiceServer) ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAssets not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_CreateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateAsset(ctx, req.(*CreateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_MoveAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).MoveAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_MoveAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).MoveAsset(ctx, req.(*MoveAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_BorrowAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BorrowAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).BorrowAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_BorrowAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).BorrowAsset(ctx, req.(*BorrowAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReturnAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReturnAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReturnAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReturnAsset(ctx, req.(*ReturnAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReportDamage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDamageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReportDamage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReportDamage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReportDamage(ctx, req.(*ReportDamageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_DisposeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisposeAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).DisposeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_DisposeAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).DisposeAsset(ctx, req.(*DisposeAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetAsset(ctx, req.(*GetAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListAssets(ctx, req.(*ListAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAsset",
			Handler:    _InventoryService_CreateAsset_Handler,
		},
		{
			MethodName: "MoveAsset",
			Handler:    _InventoryService_MoveAsset_Handler,
		},
		{
			MethodName: "BorrowAsset",
			Handler:    _InventoryService_BorrowAsset_Handler,
		},
		{
			MethodName: "ReturnAsset",
			Handler:    _InventoryService_ReturnAsset_Handler,
		},
		{
			MethodName: "ReportDamage",
			Handler:    _InventoryService_ReportDamage_Handler,
		},
		{
			MethodName: "DisposeAsset",
			Handler:    _InventoryService_DisposeAsset_Handler,
		},
		{
			MethodName: "GetAsset",
			Handler:    _InventoryService_GetAsset_Handler,
		},
		{
			MethodName: "ListAssets",
			Handler:    _InventoryService_ListAssets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventory/v1/inventory.proto",
}
