// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/registration/v1/registration.proto

package registrationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistrationService_CreateRegistration_FullMethodName  = "/registration.v1.RegistrationService/CreateRegistration"
	RegistrationService_SubmitRegistration_FullMethodName  = "/registration.v1.RegistrationService/SubmitRegistration"
	RegistrationService_VerifyRegistration_FullMethodName  = "/registration.v1.RegistrationService/VerifyRegistration"
	RegistrationService_ApproveRegistration_FullMethodName = "/registration.v1.RegistrationService/ApproveRegistration"
	RegistrationService_RejectRegistration_FullMethodName  = "/registration.v1.RegistrationService/RejectRegistration"
	RegistrationService_GetRegistration_FullMethodName     = "/registration.v1.RegistrationService/GetRegistration"
	RegistrationService_ListRegistrations_FullMethodName   = "/registration.v1.RegistrationService/ListRegistrations"
)

// RegistrationServiceClient is the client API for RegistrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistrationServiceClient interface {
	CreateRegistration(ctx context.Context, in *CreateRegistrationRequest, opts ...grpc.CallOption) (*CreateRegistrationResponse, error)
	SubmitRegistration(ctx context.Context, in *SubmitRegistrationRequest, opts ...grpc.CallOption) (*SubmitRegistrationResponse, error)
	VerifyRegistration(ctx context.Context, in *VerifyRegistrationRequest, opts ...grpc.CallOption) (*VerifyRegistrationResponse, error)
	ApproveRegistration(ctx context.Context, in *ApproveRegistrationRequest, opts ...grpc.CallOption) (*ApproveRegistrationResponse, error)
	RejectRegistration(ctx context.Context, in *RejectRegistrationRequest, opts ...grpc.CallOption) (*RejectRegistrationResponse, error)
	GetRegistration(ctx context.Context, in *GetRegistrationRequest, opts ...grpc.CallOption) (*GetRegistrationResponse, error)
	ListRegistrations(ctx context.Context, in *ListRegistrationsRequest, opts ...grpc.CallOption) (*ListRegistrationsResponse, error)
}

type registrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationServiceClient(cc grpc.ClientConnInterface) RegistrationServiceClient {
	return &registrationServiceClient{cc}
}

func (c *registrationServiceClient) CreateRegistration(ctx context.Context, in *CreateRegistrationRequest, opts ...grpc.CallOption) (*CreateRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationService_CreateRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) SubmitRegistration(ctx context.Context, in *SubmitRegistrationRequest, opts ...grpc.CallOption) (*SubmitRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationService_SubmitRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) VerifyRegistration(ctx context.Context, in *VerifyRegistrationRequest, opts ...grpc.CallOption) (*VerifyRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyRegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationService_VerifyRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) ApproveRegistration(ctx context.Context, in *ApproveRegistrationRequest, opts ...grpc.CallOption) (*ApproveRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveRegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationService_ApproveRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) RejectRegistration(ctx context.Context, in *RejectRegistrationRequest, opts ...grpc.CallOption) (*RejectRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectRegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationService_RejectRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) GetRegistration(ctx context.Context, in *GetRegistrationRequest, opts ...grpc.CallOption) (*GetRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationService_GetRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) ListRegistrations(ctx context.Context, in *ListRegistrationsRequest, opts ...grpc.CallOption) (*ListRegistrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRegistrationsResponse)
	err := c.cc.Invoke(ctx, RegistrationService_ListRegistrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServiceServer is the server API for RegistrationService service.
// All implementations must embed UnimplementedRegistrationServiceServer
// for forward compatibility.
type RegistrationServiceServer interface {
	CreateRegistration(context.Context, *CreateRegistrationRequest) (*CreateRegistrationResponse, error)
	SubmitRegistration(context.Context, *SubmitRegistrationRequest) (*SubmitRegistrationResponse, error)
	VerifyRegistration(context.Context, *VerifyRegistrationRequest) (*VerifyRegistrationResponse, error)
	ApproveRegistration(context.Context, *ApproveRegistrationRequest) (*ApproveRegistrationResponse, error)
	RejectRegistration(context.Context, *RejectRegistrationRequest) (*RejectRegistrationResponse, error)
	GetRegistration(context.Context, *GetRegistrationRequest) (*GetRegistrationResponse, error)
	ListRegistrations(context.Context, *ListRegistrationsRequest) (*ListRegistrationsResponse, error)
	mustEmbedUnimplementedRegistrationServiceServer()
}

// UnimplementedRegistrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistrationServiceServer struct{}

func (UnimplementedRegistrationServiceServer) CreateRegistration(context.Context, *CreateRegistrationRequest) (*CreateRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRegistration not implemented")
}
func (UnimplementedRegistrationServiceServer) SubmitRegistration(context.Context, *SubmitRegistrationRequest) (*SubmitRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRegistration not implemented")
}
func (UnimplementedRegistrationServiceServer) VerifyRegistration(context.Context, *VerifyRegistrationRequest) (*VerifyRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyRegistration not implemented")
}
func (UnimplementedRegistrationServiceServer) ApproveRegistration(context.Context, *ApproveRegistrationRequest) (*ApproveRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveRegistration not implemented")
}
func (UnimplementedRegistrationServiceServer) RejectRegistration(context.Context, *RejectRegistrationRequest) (*RejectRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectRegistration not implemented")
}
func (UnimplementedRegistrationServiceServer) GetRegistration(context.Context, *GetRegistrationRequest) (*GetRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegistration not implemented")
}
func (UnimplementedRegistrationServiceServer) ListRegistrations(context.Context, *ListRegistrationsRequest) (*ListRegistrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRegistrations not implemented")
}
func (UnimplementedRegistrationServiceServer) mustEmbedUnimplementedRegistrationServiceServer() {}
func (UnimplementedRegistrationServiceServer) testEmbeddedByValue()                             {}

// UnsafeRegistrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrationServiceServer will
// result in compilation errors.
type UnsafeRegistrationServiceServer interface {
	mustEmbedUnimplementedRegistrationServiceServer()
}

func RegisterRegistrationServiceServer(s grpc.ServiceRegistrar, srv RegistrationServiceServer) {
	// If the following call pancis, it indicates UnimplementedRegistrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistrationService_ServiceDesc, srv)
}

func _RegistrationService_CreateRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).CreateRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_CreateRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).CreateRegistration(ctx, req.(*CreateRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_SubmitRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).SubmitRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_SubmitRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).SubmitRegistration(ctx, req.(*SubmitRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_VerifyRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).VerifyRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_VerifyRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).VerifyRegistration(ctx, req.(*VerifyRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_ApproveRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).ApproveRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_ApproveRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).ApproveRegistration(ctx, req.(*ApproveRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_RejectRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).RejectRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_RejectRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).RejectRegistration(ctx, req.(*RejectRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_GetRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).GetRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_GetRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).GetRegistration(ctx, req.(*GetRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_ListRegistrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegistrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).ListRegistrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_ListRegistrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).ListRegistrations(ctx, req.(*ListRegistrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistrationService_ServiceDesc is the grpc.ServiceDesc for RegistrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registration.v1.RegistrationService",
	HandlerType: (*RegistrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRegistration",
			Handler:    _RegistrationService_CreateRegistration_Handler,
		},
		{
			MethodName: "SubmitRegistration",
			Handler:    _RegistrationService_SubmitRegistration_Handler,
		},
		{
			MethodName: "VerifyRegistration",
			Handler:    _RegistrationService_VerifyRegistration_Handler,
		},
		{
			MethodName: "ApproveRegistration",
			Handler:    _RegistrationService_ApproveRegistration_Handler,
		},
		{
			MethodName: "RejectRegistration",
			Handler:    _RegistrationService_RejectRegistration_Handler,
		},
		{
			MethodName: "GetRegistration",
			Handler:    _RegistrationService_GetRegistration_Handler,
		},
		{
			MethodName: "ListRegistrations",
			Handler:    _RegistrationService_ListRegistrations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/registration/v1/registration.proto",
}
