// src/events/DomainEventType.js

/**
 * Domain Event Type Catalog
 * Daftar resmi semua event dalam sistem.
 */
export const DomainEventType = {
  // --- Teaching Lifecycle ---
  TEACHING_SESSION_STARTED: 'TEACHING_SESSION_STARTED',
  TEACHING_SESSION_IN_PROGRESS: 'TEACHING_SESSION_IN_PROGRESS',
  TEACHING_SESSION_COMPLETED: 'TEACHING_SESSION_COMPLETED',
  TEACHING_SESSION_LOCKED: 'TEACHING_SESSION_LOCKED',

  // --- Teacher Presence ---
  TEACHER_CHECKED_IN: 'TEACHER_CHECKED_IN',
  TEACHER_CHECKED_OUT: 'TEACHER_CHECKED_OUT',
  TEACHER_LATE: 'TEACHER_LATE',

  // --- Attendance ---
  ATTENDANCE_DRAFT_SAVED: 'ATTENDANCE_DRAFT_SAVED',
  ATTENDANCE_SUBMITTED: 'ATTENDANCE_SUBMITTED',
  ATTENDANCE_BATCH_UPDATED: 'ATTENDANCE_BATCH_UPDATED',

  // --- Journal ---
  JOURNAL_SAVED: 'JOURNAL_SAVED',

  // --- Assessment ---
  ASSESSMENT_DRAFT_SAVED: 'ASSESSMENT_DRAFT_SAVED',
  ASSESSMENT_SUBMITTED: 'ASSESSMENT_SUBMITTED',

  // --- Student Progress ---
  TEACHER_NOTE_ADDED: 'TEACHER_NOTE_ADDED',
  HOMEROOM_NOTE_ADDED: 'HOMEROOM_NOTE_ADDED',
  ACHIEVEMENT_ADDED: 'ACHIEVEMENT_ADDED',
  VIOLATION_ADDED: 'VIOLATION_ADDED',

  // --- System ---
  AUDIT_ENTRY_CREATED: 'AUDIT_ENTRY_CREATED',
  CONTEXT_CHANGED: 'CONTEXT_CHANGED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
}
