package dlq

import (
	"testing"
	"time"

	"sekolah-platform/platform/events/types"
)

func createTestEvent() types.DomainEvent {
	return types.NewBaseEventBuilder("StudentCreated", "Student", "student-001").
		WithEventID("evt-001").
		Build()
}

func TestStore(t *testing.T) {
	d := NewMemoryDLQ(0)

	dl := DeadLetter{
		OriginalEvent: createTestEvent(),
		ConsumerName:  "edge-guru",
		LastError:     "connection timeout",
		FailureCount:  3,
	}

	if err := d.Store(dl); err != nil {
		t.Fatalf("Store failed: %v", err)
	}

	if d.Count() != 1 {
		t.Errorf("Expected count 1, got %d", d.Count())
	}
}

func TestStoreWithMaxSize(t *testing.T) {
	d := NewMemoryDLQ(2)

	for i := 0; i < 2; i++ {
		dl := DeadLetter{
			OriginalEvent: createTestEvent(),
			ConsumerName:  "consumer",
		}
		if err := d.Store(dl); err != nil {
			t.Fatalf("Store %d failed: %v", i, err)
		}
	}

	// Store ke-3 harus gagal
	dl := DeadLetter{
		OriginalEvent: createTestEvent(),
		ConsumerName:  "consumer",
	}
	if err := d.Store(dl); err == nil {
		t.Error("Expected error when DLQ full")
	}
}

func TestList(t *testing.T) {
	d := NewMemoryDLQ(0)

	for i := 0; i < 3; i++ {
		dl := DeadLetter{
			OriginalEvent: createTestEvent(),
			ConsumerName:  "consumer",
		}
		_ = d.Store(dl)
	}

	list := d.List()
	if len(list) != 3 {
		t.Errorf("Expected 3 dead letters, got %d", len(list))
	}
}

func TestListByConsumer(t *testing.T) {
	d := NewMemoryDLQ(0)

	_ = d.Store(DeadLetter{OriginalEvent: createTestEvent(), ConsumerName: "consumer-a"})
	_ = d.Store(DeadLetter{OriginalEvent: createTestEvent(), ConsumerName: "consumer-b"})
	_ = d.Store(DeadLetter{OriginalEvent: createTestEvent(), ConsumerName: "consumer-a"})

	list := d.ListByConsumer("consumer-a")
	if len(list) != 2 {
		t.Errorf("Expected 2 dead letters for consumer-a, got %d", len(list))
	}
}

func TestGet(t *testing.T) {
	d := NewMemoryDLQ(0)

	dl := DeadLetter{
		ID:            "test-id",
		OriginalEvent: createTestEvent(),
		ConsumerName:  "consumer",
	}
	_ = d.Store(dl)

	got, err := d.Get("test-id")
	if err != nil {
		t.Fatalf("Get failed: %v", err)
	}
	if got.ConsumerName != "consumer" {
		t.Errorf("Expected consumer 'consumer', got '%s'", got.ConsumerName)
	}
}

func TestGetNotFound(t *testing.T) {
	d := NewMemoryDLQ(0)

	_, err := d.Get("unknown-id")
	if err == nil {
		t.Error("Expected error for not found")
	}
}

func TestRemove(t *testing.T) {
	d := NewMemoryDLQ(0)

	dl := DeadLetter{
		ID:            "test-id",
		OriginalEvent: createTestEvent(),
		ConsumerName:  "consumer",
	}
	_ = d.Store(dl)

	if err := d.Remove("test-id"); err != nil {
		t.Fatalf("Remove failed: %v", err)
	}
	if d.Count() != 0 {
		t.Errorf("Expected count 0 after remove, got %d", d.Count())
	}
}

func TestClear(t *testing.T) {
	d := NewMemoryDLQ(0)

	for i := 0; i < 5; i++ {
		_ = d.Store(DeadLetter{OriginalEvent: createTestEvent()})
	}

	if err := d.Clear(); err != nil {
		t.Fatalf("Clear failed: %v", err)
	}
	if d.Count() != 0 {
		t.Errorf("Expected count 0 after clear, got %d", d.Count())
	}
}

func TestAutoGeneratedID(t *testing.T) {
	d := NewMemoryDLQ(0)

	dl := DeadLetter{
		OriginalEvent: createTestEvent(),
		ConsumerName:  "consumer",
	}
	_ = d.Store(dl)

	list := d.List()
	if len(list) != 1 {
		t.Fatalf("Expected 1 dead letter, got %d", len(list))
	}
	if list[0].ID == "" {
		t.Error("Expected auto-generated ID")
	}
	if list[0].FailedAt.IsZero() {
		t.Error("Expected FailedAt to be set")
	}
}

func TestFailedAtAutoSet(t *testing.T) {
	d := NewMemoryDLQ(0)

	before := time.Now()
	dl := DeadLetter{
		OriginalEvent: createTestEvent(),
		ConsumerName:  "consumer",
	}
	_ = d.Store(dl)
	after := time.Now()

	list := d.List()
	if list[0].FailedAt.Before(before) || list[0].FailedAt.After(after) {
		t.Error("Expected FailedAt to be auto-set to current time")
	}
}
